In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
dataset = pd.read_csv('healthcare_dataset_stroke_data.csv',sep=',')
X= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

# New Section

In [3]:
X

array([['Male', 67.0, 0, ..., 228.69, 36.6, 'formerly smoked'],
       ['Female', 61.0, 0, ..., 202.21, nan, 'never smoked'],
       ['Male', 80.0, 0, ..., 105.92, 32.5, 'never smoked'],
       ...,
       ['Female', 35.0, 0, ..., 82.99, 30.6, 'never smoked'],
       ['Male', 51.0, 0, ..., 166.29, 25.6, 'formerly smoked'],
       ['Female', 44.0, 0, ..., 85.28, 26.2, 'Unknown']], dtype=object)

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])
X[:, 4] = le.fit_transform(X[:, 4])
X[:, 6] = le.fit_transform(X[:, 6])

In [5]:
X

array([[1, 67.0, 0, ..., 228.69, 36.6, 'formerly smoked'],
       [0, 61.0, 0, ..., 202.21, nan, 'never smoked'],
       [1, 80.0, 0, ..., 105.92, 32.5, 'never smoked'],
       ...,
       [0, 35.0, 0, ..., 82.99, 30.6, 'never smoked'],
       [1, 51.0, 0, ..., 166.29, 25.6, 'formerly smoked'],
       [0, 44.0, 0, ..., 85.28, 26.2, 'Unknown']], dtype=object)

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5,9])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
X

array([[0.0, 0.0, 1.0, ..., 1, 228.69, 36.6],
       [0.0, 0.0, 0.0, ..., 0, 202.21, nan],
       [0.0, 0.0, 1.0, ..., 0, 105.92, 32.5],
       ...,
       [0.0, 0.0, 0.0, ..., 0, 82.99, 30.6],
       [0.0, 0.0, 1.0, ..., 0, 166.29, 25.6],
       [1.0, 0.0, 0.0, ..., 1, 85.28, 26.2]], dtype=object)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
ann = tf.keras.models.Sequential()

In [11]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [12]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

In [13]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [14]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [15]:
ann.fit(X_train, y_train, batch_size = 8, epochs = 50)

Epoch 1/50
511/511 [==============================] - 2s 2ms/step - loss: nan - accuracy: 0.9521
Epoch 2/50
511/511 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9523
Epoch 3/50
511/511 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9523
Epoch 4/50
511/511 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9523
Epoch 5/50
511/511 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9523
Epoch 6/50
511/511 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9523
Epoch 7/50
511/511 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9523
Epoch 8/50
511/511 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9523
Epoch 9/50
511/511 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9523
Epoch 10/50
511/511 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.9523
Epoch 11/50
511/511 [========

In [16]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

32/32 [==============================] - 0s 2ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[968   0]
 [ 54   0]]


0.9471624266144814